version: '3.8'

services:
  # Service Base de Données
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=forum_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password_secret
    restart: always

  # Service Django
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/app  # Important: Synchronisation en temps réel (Hot Reload)
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=forum_db
      - DB_USER=admin
      - DB_PASSWORD=password_secret
      - DB_HOST=db  # Le nom du service ci-dessus
      - DB_PORT=5432

volumes:
  postgres_data: # Pour ne pas perdre les données quand on éteint Docker