services:
  # Service Base de Données
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always

  # Service Django
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/app  # Important: Synchronisation en temps réel (Hot Reload)
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}  # Le nom du service ci-dessus
      - DB_PORT=${DB_PORT}
      - GOOGLE_AI_API_KEY=${GOOGLE_AI_API_KEY}

volumes:
  postgres_data: # Pour ne pas perdre les données quand on éteint Docker