# Generated by Django 5.2.8 on 2025-11-23 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Homme'), ('F', 'Femme'), ('O', 'Autre')], default='O', max_length=1, verbose_name='Genre'),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.CharField(default='Polytech Lyon', max_length=200, verbose_name='École'),
        ),
    ]
