# Generated by Django 5.2.8 on 2025-11-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_student_gender_student_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school_url',
            field=models.URLField(blank=True, null=True, verbose_name="Site de l'école"),
        ),
    ]
