# Generated by Django 5.2.8 on 2025-11-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_student_school_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='availability',
            field=models.CharField(blank=True, max_length=100, verbose_name='Disponibilité'),
        ),
        migrations.AddField(
            model_name='student',
            name='duration',
            field=models.CharField(blank=True, max_length=100, verbose_name='Durée souhaitée'),
        ),
        migrations.AddField(
            model_name='student',
            name='education',
            field=models.TextField(blank=True, verbose_name='Éducation'),
        ),
        migrations.AddField(
            model_name='student',
            name='experience',
            field=models.TextField(blank=True, verbose_name='Expérience'),
        ),
    ]
