# Generated by Django 5.2.8 on 2025-11-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_student_availability_student_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hobbies',
            field=models.TextField(blank=True, verbose_name='Loisirs'),
        ),
        migrations.AddField(
            model_name='student',
            name='theme',
            field=models.CharField(choices=[('light', 'Clair'), ('dark', 'Sombre')], default='dark', max_length=10, verbose_name='Thème'),
        ),
    ]
