# Generated by Django 5.2.8 on 2025-11-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_student_hobbies_student_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='github_url',
            field=models.URLField(blank=True, null=True, verbose_name='Profil GitHub'),
        ),
        migrations.AddField(
            model_name='student',
            name='languages',
            field=models.CharField(blank=True, max_length=200, verbose_name='Langues'),
        ),
        migrations.AddField(
            model_name='student',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True, verbose_name='Profil LinkedIn'),
        ),
        migrations.AddField(
            model_name='student',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='Localisation'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='student',
            name='website_url',
            field=models.URLField(blank=True, null=True, verbose_name='Site personnel'),
        ),
    ]
