# Generated by Django 5.2.8 on 2025-12-05 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_student_github_url_student_languages_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='swipe',
            options={'verbose_name': 'Swipe Étudiant', 'verbose_name_plural': 'Swipes Étudiants'},
        ),
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='company',
            name='benefits',
            field=models.TextField(blank=True, verbose_name='Avantages proposés'),
        ),
        migrations.AddField(
            model_name='company',
            name='employees',
            field=models.IntegerField(blank=True, null=True, verbose_name="Nombre d'employés"),
        ),
        migrations.AddField(
            model_name='company',
            name='founded_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Année de création'),
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='swipe',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_swipes', to='core.company'),
        ),
        migrations.CreateModel(
            name='CompanySwipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('right', 'Intéressé'), ('left', 'Pas intéressé')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes', to='core.company')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_swipes', to='core.student')),
            ],
            options={
                'verbose_name': 'Swipe Entreprise',
                'verbose_name_plural': 'Swipes Entreprises',
                'unique_together': {('company', 'student')},
            },
        ),
    ]
