# Generated by Django 5.2.8 on 2025-12-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_internshipoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipoffer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
