# Generated by Django 5.2.8 on 2025-12-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_internshipoffer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Photo de profil'),
        ),
        migrations.AddField(
            model_name='student',
            name='photo_visible',
            field=models.BooleanField(default=True, verbose_name='Photo visible par les entreprises'),
        ),
    ]
