# Generated by Django 5.2.9 on 2025-12-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_student_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['student_priority'], 'verbose_name': 'Match', 'verbose_name_plural': 'Matchs'},
        ),
        migrations.AddField(
            model_name='match',
            name='student_priority',
            field=models.PositiveIntegerField(default=0, verbose_name='Priorité étudiant'),
        ),
    ]
