# Generated by Django 5.2.8 on 2025-12-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_student_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='about',
            field=models.TextField(blank=True, verbose_name='À propos'),
        ),
        migrations.AlterField(
            model_name='student',
            name='education',
            field=models.JSONField(blank=True, default=list, verbose_name='Éducation'),
        ),
        migrations.AlterField(
            model_name='student',
            name='experience',
            field=models.JSONField(blank=True, default=list, verbose_name='Expérience'),
        ),
        migrations.AlterField(
            model_name='student',
            name='hobbies',
            field=models.JSONField(blank=True, default=list, verbose_name='Loisirs'),
        ),
        migrations.AlterField(
            model_name='student',
            name='languages',
            field=models.JSONField(blank=True, default=list, verbose_name='Langues'),
        ),
    ]
