# Generated by Django 5.2.9 on 2025-12-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_student_about_alter_student_education_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
        migrations.AddField(
            model_name='student',
            name='role',
            field=models.CharField(default='Étudiant', max_length=100, verbose_name='Rôle (Étudiant, Apprenti...)'),
        ),
    ]
