# Generated by Django 5.2.9 on 2025-12-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_student_gender_student_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='role',
            field=models.CharField(choices=[('etudiant', 'Étudiant'), ('apprenti', 'Apprenti'), ('alternant', 'Alternant')], default='etudiant', max_length=50, verbose_name='Rôle'),
        ),
    ]
