# Generated by Django 5.2.9 on 2025-12-12 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_student_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='preferences',
        ),
    ]
