# Generated by Django 5.2.9 on 2025-12-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_student_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='role',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Type de contrat'),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.CharField(blank=True, max_length=50, verbose_name='Année'),
        ),
    ]
