# Generated by Django 5.2.11 on 2026-02-04 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_merge_0011_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du forum')),
                ('date', models.DateField(verbose_name='Date du forum')),
                ('start_time', models.TimeField(default='09:00', verbose_name='Heure de début')),
                ('end_time', models.TimeField(default='17:00', verbose_name='Heure de fin')),
                ('location', models.CharField(max_length=255, verbose_name='Lieu')),
                ('address', models.TextField(blank=True, verbose_name='Adresse complète')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Forum actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Forum',
                'verbose_name_plural': 'Forums',
                'ordering': ['-date'],
            },
        ),
    ]
