# Generated by Django 5.2.11 on 2026-02-11 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_forum_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='Score (0-100)')),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_scores', to='core.internshipoffer')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_scores', to='core.student')),
            ],
            options={
                'verbose_name': 'Score de matching',
                'verbose_name_plural': 'Scores de matching',
                'ordering': ['-score'],
                'unique_together': {('student', 'offer')},
            },
        ),
    ]
